[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
contracts = "9xpLht8FtpZgEGFpHpC6W3pupoHbfTsBMytj7CqxJ8us"
ai_vault = "74Er4xSaRKQbDL1X8UUjYP9M4vXNZUZR36qeMUdH7RU9"

[programs.devnet]
contracts = "9xpLht8FtpZgEGFpHpC6W3pupoHbfTsBMytj7CqxJ8us"
ai_vault = "74Er4xSaRKQbDL1X8UUjYP9M4vXNZUZR36qeMUdH7RU9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
